// The evaluator WASM package is generated by scripts/build-evaluator.mjs (wasm-pack --target web)
// into src/logic/wasm/. It is absent at typecheck/test time; this ambient declaration lets
// loadEvaluator() type-check, and consumers mock loadEvaluator so the real module is never resolved.
declare module './wasm/questionnaire_expr_web.js' {
  const init: (input?: unknown) => Promise<unknown>
  export default init
  export function evaluate_condition(expr: string, bindings: unknown): boolean
  export function reversed(value: number, min: number, max: number): number
  export function compare(cmp: string, response: unknown, expected: unknown): boolean
  export function check_expression(expr: string): string | undefined
}
