[workspace]
resolver = "2"
members = ["abi", "engine", "scorers/phq9", "scorers/gad7", "scorers/swls", "scorers/who5", "scorers/dass21", "scorers/spin", "scorers/ocir", "scorers/panas", "scorers/fs", "scorers/rrs", "scorers/rses", "scorers/brs", "scorers/gq6", "scorers/tils", "scorers/pss", "scorers/cage", "scorers/hama", "scorers/icg", "scorers/gse", "scorers/erq", "scorers/spane"]

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
strip = true
