// Build a data-driven Scorer from a declarative authoring spec.
//
//   node scripts/build-scorer.mjs <id>
//
// Reads specs/<id>.json, generates scorers/<id>/ (a thin crate embedding the engine_spec and
// calling scorer-engine), builds it to wasm, writes dist-wasm/<id>.wasm, derives the Scorer
// entity dist-entities/scr_<id>.json (inputs + output_schema + implementations sha256 +
// test_cases), and runs the conformance runner. Exit 0 iff conformant.
import { execSync } from 'node:child_process'
import { copyFileSync, mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..') // questionnaire-scorer/

const id = process.argv[2]
if (!id || !/^[a-z][a-z0-9]*$/.test(id)) {
  console.error('usage: node scripts/build-scorer.mjs <id>   (id: lowercase alnum, e.g. gad7)')
  process.exit(2)
}

const spec = JSON.parse(readFileSync(join(root, 'specs', `${id}.json`), 'utf8'))
const eng = spec.engine_spec
const scorerId = spec.scorer_id || `scr_${id}`

// ---- 1. generate the thin per-instrument crate ----
const crateDir = join(root, 'scorers', id)
mkdirSync(join(crateDir, 'src'), { recursive: true })
writeFileSync(join(crateDir, 'spec.json'), JSON.stringify(eng))
writeFileSync(join(crateDir, 'Cargo.toml'), `[package]
name = "${id}"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
scorer-abi = { path = "../../abi" }
scorer-engine = { path = "../../engine" }
serde_json = "1"
`)
writeFileSync(join(crateDir, 'src', 'lib.rs'), `// GENERATED by scripts/build-scorer.mjs from specs/${id}.json — do not edit.
use serde_json::Value;
const SPEC: &str = include_str!("../spec.json");
fn score(input: &Value) -> Result<Value, String> { scorer_engine::score(SPEC, input) }
scorer_abi::scorer!(score);
`)

// ensure the crate is a workspace member (shared target/ + cargo -p)
const wsPath = join(root, 'Cargo.toml')
let ws = readFileSync(wsPath, 'utf8')
if (!ws.includes(`"scorers/${id}"`)) {
  ws = ws.replace(/members = \[([^\]]*)\]/, (_m, inner) =>
    `members = [${inner.replace(/\s+$/, '')}, "scorers/${id}"]`)
  writeFileSync(wsPath, ws)
}

// ---- 2. build wasm ----
execSync(`. "$HOME/.cargo/env" && cargo build -p ${id} --target wasm32-unknown-unknown --release`, {
  cwd: root, stdio: 'inherit', shell: '/bin/bash',
})
const built = join(root, 'target', 'wasm32-unknown-unknown', 'release', `${id}.wasm`)
const distDir = join(root, 'dist-wasm')
mkdirSync(distDir, { recursive: true })
const wasmOut = join(distDir, `${id}.wasm`)
copyFileSync(built, wasmOut)
const sha = createHash('sha256').update(readFileSync(wasmOut)).digest('hex')

// ---- 3. derive the Scorer entity ----
const items = [...new Set(eng.scores.flatMap((s) => s.items))]
const [lo, hi] = eng.item_range || [null, null]
const itemSchema = { type: 'integer' }
if (lo != null) itemSchema.minimum = lo
if (hi != null) itemSchema.maximum = hi
const inputs = {
  type: 'object',
  properties: {
    scored_responses: {
      type: 'object',
      patternProperties: { [`^(${items.map((i) => i.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|')})$`]: itemSchema },
    },
  },
  required: ['scored_responses'],
}
const scoreProps = {}
for (const s of eng.scores) {
  const props = { value: { type: 'number' } }
  const required = ['value']
  if (s.bands && s.bands.length) {
    props.severity = { type: 'string', enum: [...new Set(s.bands.map((b) => b.severity))] }
    props.band = {
      type: 'object',
      properties: { min: { type: 'number' }, max: { type: 'number' }, label: { type: 'string' } },
      required: ['min', 'max', 'label'],
    }
  }
  scoreProps[s.key] = { type: 'object', properties: props, required }
}
const output_schema = {
  type: 'object',
  properties: {
    scores: { type: 'object', properties: scoreProps, required: Object.keys(scoreProps) },
    missing_count: { type: 'integer', minimum: 0 },
  },
  required: ['scores', 'missing_count'],
}
const entity = {
  id: scorerId,
  name: spec.name,
  content: { en: { status: spec.status || 'needs-review', name: spec.name, description: spec.description } },
  ...(spec.publication ? { publication: spec.publication } : {}),
  inputs,
  output_schema,
  implementations: [
    { kind: 'wasm', url: `https://behaverse.org/scorers/${id}/scorer.wasm`, sha256: sha },
  ],
  test_cases: spec.test_cases,
}
const entDir = join(root, 'dist-entities')
mkdirSync(entDir, { recursive: true })
const entPath = join(entDir, `${scorerId}.json`)
writeFileSync(entPath, JSON.stringify(entity, null, 2) + '\n')
console.log(`built ${id}.wasm sha256 ${sha}`)
console.log(`wrote ${entPath}`)

// ---- 4. conformance ----
const cli = join(root, 'host', 'dist', 'cli.js')
if (!existsSync(cli)) { console.error('host CLI not built — run `npm --prefix host run build`'); process.exit(2) }
execSync(`node ${JSON.stringify(cli)} ${JSON.stringify(entPath)} ${JSON.stringify(wasmOut)}`, {
  cwd: root, stdio: 'inherit',
})
