// GENERATED by scripts/build-scorer.mjs from specs/cc.json — do not edit.
use serde_json::Value;
const SPEC: &str = include_str!("../spec.json");
fn score(input: &Value) -> Result<Value, String> { scorer_engine::score(SPEC, input) }
scorer_abi::scorer!(score);
